SELECT
       REPLY_NO
     , REPLY_CONTENT
     , USER_ID
     , TO_CHAR(CREATE_DATE, 'YY/MM/DD HH:MI') "CREATE_DATE"
  FROM REPLY R
  JOIN MEMBER ON (REPLY_WRITER = USER_NO)
 WHERE R.STATUS = 'Y'
   AND REF_BNO = ?
 ORDER
    BY REPLY_NO DESC